databases:
  - name: flow-desk
    databaseName: flow-desk
    user: flow-desk_user
    plan: free

services:
  - type: web
    name: flow-desk # the name of this service, eg hello-world
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - KEY: DATABASE_URL
        fromDatabase:
          name: flow-desk
          property: connectionString
      - key: RAILS_MASTER_KEY 
        sync: false
